### ISSUE TITLE
How to configure CXXNET for more than 1 fullc path ? 

### ISSUE THREAD

**Issue by pchankh** [antinucleon/cxxnet#26]
Thanks for the great work in CXXNet... I would like to find out how can we configure cxxnet to have more than 1 full path (i.e. split from max_pooling layer) and going into 2 separate fullc path and layer recombining into a fullc layer with softmax.

Appreciate if the authors can help advise.

Thanks
Dr Patrick

**Comment by antinucleon** [comment]
Supported in v0.2 already
