### ISSUE TITLE
"decoding fail"

### ISSUE THREAD

**Issue by hothHowler** [antinucleon/cxxnet#27]
I am running the "kaggle_bowl" example and get an error "decoding fail" (full message appended below).  I saw on the kaggle forum that this means opencv can't decode image in the binary file generated by im2bin. Does this mean im2bin is not producing the expected output??

$ ../../bin/cxxnet bowl.conf
Use CUDA Device 0: Tesla C1060
CXXNetTrainer, devCPU=0
ConvolutionLayer: nstep=256
ConvolutionLayer: nstep=256
ConvolutionLayer: nstep=128
SGDUpdater: eta=0.010000, mom=0.900000
SGDUpdater: eta=0.020000, mom=0.900000
SGDUpdater: eta=0.010000, mom=0.900000
SGDUpdater: eta=0.020000, mom=0.900000
SGDUpdater: eta=0.010000, mom=0.900000
SGDUpdater: eta=0.020000, mom=0.900000
SGDUpdater: eta=0.010000, mom=0.900000
SGDUpdater: eta=0.020000, mom=0.900000
SGDUpdater: eta=0.010000, mom=0.900000
SGDUpdater: eta=0.020000, mom=0.900000
SGDUpdater: eta=0.010000, mom=0.900000
SGDUpdater: eta=0.020000, mom=0.900000
node[0].shape: 256,3,48,48
node[1].shape: 256,96,12,12
node[2].shape: 256,96,12,12
node[3].shape: 256,96,6,6
node[4].shape: 256,128,8,8
node[5].shape: 256,128,8,8
node[6].shape: 256,128,8,8
node[7].shape: 256,128,8,8
node[8].shape: 256,128,4,4
node[9].shape: 1,1,256,2048
node[10].shape: 1,1,256,512
node[11].shape: 1,1,256,512
node[12].shape: 1,1,256,512
node[13].shape: 1,1,256,512
node[14].shape: 1,1,256,121
ThreadImagePageIterator:image_list=./train.lst, bin=./train.bin
cannot find models/image_mean.bin: create mean image, this will take some time...
Error:decoding fail

**Comment by antinucleon** [comment]
please check your opencv and whether you made other files in train.lst

**Comment by hothHowler** [comment]
I went through the data preparation steps again and this seems to have fixed my problem. 
Thanks!
