### ISSUE TITLE
Compiling with Atlas

### ISSUE THREAD

**Issue by deepusenan** [antinucleon/cxxnet#31]
I was trying to link an ATLAS implementation using  -latlas instead of -lblas in the makefile 

it gets me the following error..  
./mshadow/mshadow/tensor_expr_engine-inl.hpp:278: undefined reference to `cblas_sgemm'

Google gave me the result
http://stackoverflow.com/questions/1137483/c-c-linking-error 
Basically advised me to have extern "C"  declaration..

When i see it in mshadow, it already has an extern "C" there..    Could somebody help..

Thanks
Deepu

**Comment by tqchen** [comment]
Try use -lcblas

**Comment by deepusenan** [comment]
Dear Chen,
     thanks for the quick response..  i don't have a cuda GPU and was trying to use atlas since it has some parallel processing capability..  It looks like even lcblas do not have parallel computation.. 

Thanks 
Deepu

**Comment by tqchen** [comment]
You can use openblas

On Saturday, January 17, 2015, deepusenan <notifications@github.com> wrote:

> Dear Chen,
> thanks for the quick response.. i don't have a cuda GPU and was trying to
> use atlas since it has some parallel processing capability.. It looks like
> even lcblas do not have parallel computation..
>
> Thanks
> Deepu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antinucleon/cxxnet/issues/31#issuecomment-70372055>.
>


-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by deepusenan** [comment]
Dear Chen, Thank you.  It worked.
