### ISSUE TITLE
Error building cxxnet using Ubuntu 14.04

### ISSUE THREAD

**Issue by DataCentric1** [antinucleon/cxxnet#36]
I'm building cxxnet in CPU only mode using ATLAS blas. I replaced makefile with make/Cblas.cpu.ml and Cpu_only.mk (tried with both), but get this error "undefined reference to symbol 'sem_post@@GLIBC_2.2.5'"

Any suggestions on what to do? Thanks!

g++ -Wall -g -O3 -msse3 -Wno-unknown-pragmas -funroll-loops -I./mshadow/ -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_SSE=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_CBLAS=1  -o bin/cxxnet cxxnet/cxxnet_main.cpp cxxnet_data.o cxxnet_nnet_cpu.o -lm -lz `pkg-config --libs opencv` -lcblas
/usr/bin/ld: cxxnet_data.o: undefined reference to symbol 'sem_post@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [bin/cxxnet] Error 1

**Comment by tqchen** [comment]
You need to add-lpthread to command line

Tianqi

**Comment by DataCentric1** [comment]
Hi Tiangi, I tried it, but still getting the same error. Ran "make -lpthread" from the cxxnet folder. Also tried adding it to the cflags in makefile, didn't help.

-Harsha

**Comment by DataCentric1** [comment]
Figured it out, need to add -lpthread to LDFLAGS in the Makefile.  

Tianqi, thanks for pointing out the need for -lpthread.

-Harsha
