### ISSUE TITLE
Possible data augmentation: brightness and/or contrast

### ISSUE THREAD

**Issue by bame55** [antinucleon/cxxnet#44]
After taking a look at the work you're doing in the V2-refactor branch - very nice by the way! - I thought it might be worth mentioning another possible augmentation: random brightness and/or contrast changes.  It would be very simple to do using OpenCV's Mat::convertTo.

Reference: http://docs.opencv.org/modules/core/doc/basic_structures.html#void%20Mat::convertTo%28OutputArray%20m,%20int%20rtype,%20double%20alpha,%20double%20beta%29%20const

Tutorial: http://docs.opencv.org/doc/tutorials/core/basic_linear_transform/basic_linear_transform.html#brightness-and-contrast-adjustments

**Comment by winstywang** [comment]
It is added in the latest commit https://github.com/antinucleon/cxxnet/commit/83954fb7873d233cb92d5ad3f336c85553406fed in V2-refactor. Please consult the docs for usage.
